CREATE TABLE IF NOT EXISTS "roles" (
CREATE TABLE IF NOT EXISTS "users" (
CREATE TABLE IF NOT EXISTS "width" (
CREATE TABLE IF NOT EXISTS "aspect_ratio" (
CREATE TABLE IF NOT EXISTS "inch" (
CREATE TABLE IF NOT EXISTS "manufacturer" (
CREATE TABLE IF NOT EXISTS "ply_rating" (
CREATE TABLE IF NOT EXISTS "alembic_version" (
CREATE TABLE IF NOT EXISTS "input_page" (
CREATE TABLE IF NOT EXISTS "search_page" (
CREATE TABLE IF NOT EXISTS "dispatch_history" (
CREATE TABLE IF NOT EXISTS "edit_page" (
CREATE TABLE IF NOT EXISTS "history_page" (
CREATE TABLE IF NOT EXISTS "alert_page" (
INSERT INTO alembic_version VALUES ('7346ce46d166');
