"""Add tracking columns to Width

Revision ID: 0335770878fb
Revises: c1d9b3470368
Create Date: 2025-04-04 22:23:29.464075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0335770878fb'
down_revision = 'c1d9b3470368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aspect_ratio', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inch', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('manufacturer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('ply_rating', 'created_at')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.add_column('width', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('width', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('width', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.alter_column('width', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'width', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'width', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'width', type_='foreignkey')
    op.drop_constraint(None, 'width', type_='foreignkey')
    op.alter_column('width', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_column('width', 'updated_by')
    op.drop_column('width', 'updated_at')
    op.drop_column('width', 'created_by')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('ply_rating', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('manufacturer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('inch', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('aspect_ratio', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
