"""Add tracking columns to Inch

Revision ID: 5890b4df470f
Revises: cd2398a28ec6
Create Date: 2025-04-04 22:31:03.944952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5890b4df470f'
down_revision = 'cd2398a28ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inch', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('inch', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('inch', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inch', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'inch', 'users', ['created_by'], ['id'])
    op.add_column('manufacturer', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('manufacturer', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('manufacturer', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manufacturer', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'manufacturer', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufacturer', type_='foreignkey')
    op.drop_constraint(None, 'manufacturer', type_='foreignkey')
    op.drop_column('manufacturer', 'updated_by')
    op.drop_column('manufacturer', 'updated_at')
    op.drop_column('manufacturer', 'created_by')
    op.drop_constraint(None, 'inch', type_='foreignkey')
    op.drop_constraint(None, 'inch', type_='foreignkey')
    op.drop_column('inch', 'updated_by')
    op.drop_column('inch', 'updated_at')
    op.drop_column('inch', 'created_by')
    # ### end Alembic commands ###
