"""Recreate database with InputPage and all tables

Revision ID: 5ac52fdb06e4
Revises: 
Create Date: 2024-12-17 17:15:13.316969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac52fdb06e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aspect_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ply_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('width',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Integer(), nullable=True),
    sa.Column('inch', sa.Integer(), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_ratio'], ['aspect_ratio.id'], ),
    sa.ForeignKeyConstraint(['inch'], ['inch.id'], ),
    sa.ForeignKeyConstraint(['width'], ['width.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.Integer(), nullable=False),
    sa.Column('inch', sa.Integer(), nullable=False),
    sa.Column('other_details', sa.String(), nullable=True),
    sa.Column('manufacturing_year', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.Integer(), nullable=False),
    sa.Column('tread_depth', sa.Integer(), nullable=True),
    sa.Column('uneven_wear', sa.Integer(), nullable=True),
    sa.Column('ply_rating', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_dispatched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_ratio'], ['aspect_ratio.id'], ),
    sa.ForeignKeyConstraint(['inch'], ['inch.id'], ),
    sa.ForeignKeyConstraint(['manufacturer'], ['manufacturer.id'], ),
    sa.ForeignKeyConstraint(['ply_rating'], ['ply_rating.id'], ),
    sa.ForeignKeyConstraint(['width'], ['width.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Integer(), nullable=True),
    sa.Column('inch', sa.Integer(), nullable=True),
    sa.Column('inventory_count', sa.Integer(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_ratio'], ['aspect_ratio.id'], ),
    sa.ForeignKeyConstraint(['inch'], ['inch.id'], ),
    sa.ForeignKeyConstraint(['width'], ['width.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tire_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('dispatch_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tire_id'], ['input_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tire_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('edit_date', sa.Date(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tire_id'], ['input_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tire_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('edit_date', sa.Date(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tire_id'], ['input_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_page')
    op.drop_table('edit_page')
    op.drop_table('dispatch_history')
    op.drop_table('search_page')
    op.drop_table('input_page')
    op.drop_table('alert_page')
    op.drop_table('width')
    op.drop_table('user')
    op.drop_table('ply_rating')
    op.drop_table('manufacturer')
    op.drop_table('inch')
    op.drop_table('aspect_ratio')
    # ### end Alembic commands ###
