"""add FK to last_edited_by

Revision ID: 6a66bf989406
Revises: 9488f762bed3
Create Date: 2025-05-07 23:36:50.686582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a66bf989406'
down_revision = '9488f762bed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'input_page', 'users', ['last_edited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'input_page', type_='foreignkey')
    # ### end Alembic commands ###
