"""Recreate migrations

Revision ID: 8e2ebcff4db4
Revises: 
Create Date: 2025-02-28 20:40:38.072029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e2ebcff4db4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tire_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('edit_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tire_id'], ['input_page.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('dispatch_history_user_id_fkey', 'dispatch_history', type_='foreignkey')
    op.create_foreign_key(None, 'dispatch_history', 'users', ['user_id'], ['id'])
    op.alter_column('edit_page', 'edit_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('input_page', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('input_page', 'other_details',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('input_page', 'is_dispatched',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'input_page', 'ply_rating', ['ply_rating'], ['id'])
    op.create_foreign_key(None, 'input_page', 'manufacturer', ['manufacturer'], ['id'])
    op.create_foreign_key(None, 'input_page', 'width', ['width'], ['id'])
    op.create_foreign_key(None, 'input_page', 'aspect_ratio', ['aspect_ratio'], ['id'])
    op.create_foreign_key(None, 'input_page', 'inch', ['inch'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'input_page', type_='foreignkey')
    op.drop_constraint(None, 'input_page', type_='foreignkey')
    op.drop_constraint(None, 'input_page', type_='foreignkey')
    op.drop_constraint(None, 'input_page', type_='foreignkey')
    op.drop_constraint(None, 'input_page', type_='foreignkey')
    op.alter_column('input_page', 'is_dispatched',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('input_page', 'other_details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('input_page', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('edit_page', 'edit_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'dispatch_history', type_='foreignkey')
    op.create_foreign_key('dispatch_history_user_id_fkey', 'dispatch_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('edit_history')
    # ### end Alembic commands ###
