"""add created_by to input_page

Revision ID: 9488f762bed3
Revises: 5890b4df470f
Create Date: 2025-05-07 21:40:17.378439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9488f762bed3'
down_revision = '5890b4df470f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_page', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'input_page', 'users', ['created_by'], ['id'])
    op.alter_column('ply_rating', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ply_rating', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'input_page', type_='foreignkey')
    op.drop_column('input_page', 'created_by')
    # ### end Alembic commands ###
