"""Remove is_custom from ply_rating (retry)

Revision ID: c1d9b3470368
Revises: 8e2ebcff4db4
Create Date: 2025-03-30 00:04:36.896266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d9b3470368'
down_revision = '8e2ebcff4db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ply_rating', 'is_custom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ply_rating', sa.Column('is_custom', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
