"""Add tracking columns to AspectRatio

Revision ID: cd2398a28ec6
Revises: 0335770878fb
Create Date: 2025-04-04 22:25:57.295794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2398a28ec6'
down_revision = '0335770878fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aspect_ratio', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('aspect_ratio', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('aspect_ratio', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aspect_ratio', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'aspect_ratio', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aspect_ratio', type_='foreignkey')
    op.drop_constraint(None, 'aspect_ratio', type_='foreignkey')
    op.drop_column('aspect_ratio', 'updated_by')
    op.drop_column('aspect_ratio', 'updated_at')
    op.drop_column('aspect_ratio', 'created_by')
    # ### end Alembic commands ###
